version: '3.8'

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
    networks:
      - pintest
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=mypasswd
      - MYSQL_PASSWORD=mypasswd
    networks:
      - pintest
volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

networks:
  pintest: 